sonar.projectKey=ACEest-Fitness
sonar.projectName=ACEest Fitness & Gym
sonar.projectVersion=3.2.4
sonar.sources=app.py
sonar.tests=test_app.py
sonar.language=py
sonar.python.coverage.reportPaths=coverage.xml
sonar.host.url=http://localhost:9000
sonar.sourceEncoding=UTF-8
sonar.exclusions=venv/**,**/__pycache__/**
