apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-blue
  namespace: aceest
  labels:
    app: aceest-fitness
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aceest-fitness
      version: blue
  template:
    metadata:
      labels:
        app: aceest-fitness
        version: blue
    spec:
      containers:
        - name: aceest
          image: abhishekmangl/aceest-fitness:latest
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "250m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-green
  namespace: aceest
  labels:
    app: aceest-fitness
    version: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aceest-fitness
      version: green
  template:
    metadata:
      labels:
        app: aceest-fitness
        version: green
    spec:
      containers:
        - name: aceest
          image: abhishekmangl/aceest-fitness:latest
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: aceest-bg-service
  namespace: aceest
spec:
  selector:
    app: aceest-fitness
    version: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30081
  type: NodePort
